# Generated by Django 5.2.4 on 2025-07-28 23:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('type', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة خصم'), ('bank_transfer', 'تحويل بنكي'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('digital_wallet', 'محفظة رقمية')], max_length=20, verbose_name='نوع الدفع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة رسوم المعالجة')),
                ('processing_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='رسوم المعالجة الثابتة')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الحد الأدنى للمبلغ')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للمبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='رسوم المعالجة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي'), ('refunded', 'مسترد'), ('partially_refunded', 'مسترد جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='معرف المعاملة')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='استجابة البوابة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='الطلب')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الاسترداد')),
                ('reason', models.CharField(choices=[('customer_request', 'طلب العميل'), ('defective_product', 'منتج معيب'), ('wrong_item', 'عنصر خاطئ'), ('not_as_described', 'لا يطابق الوصف'), ('damaged_shipping', 'تلف أثناء الشحن'), ('other', 'أخرى')], max_length=20, verbose_name='سبب الاسترداد')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاسترداد')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='معرف معاملة الاسترداد')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='استجابة البوابة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='الدفعة')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
            ],
            options={
                'verbose_name': 'استرداد',
                'verbose_name_plural': 'الاستردادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'إيداع'), ('debit', 'سحب')], max_length=10, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.CharField(choices=[('refund', 'استرداد'), ('cashback', 'استرداد نقدي'), ('bonus', 'مكافأة'), ('purchase', 'شراء'), ('withdrawal', 'سحب'), ('adjustment', 'تعديل')], max_length=20, verbose_name='سبب المعاملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='المعرف المرجعي')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد قبل المعاملة')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد بعد المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'معاملة محفظة',
                'verbose_name_plural': 'معاملات المحافظ',
                'ordering': ['-created_at'],
            },
        ),
    ]
