# Generated by Django 5.2.4 on 2025-07-28 23:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('is_answered', models.BooleanField(default=False, verbose_name='تم الإجابة')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('is_seller', models.BooleanField(default=False, verbose_name='من البائع')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'ordering': ['-is_seller', '-helpful_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المراجعة')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='شراء محقق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem', verbose_name='عنصر الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التسمية التوضيحية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='المراجعة')),
            ],
            options={
                'verbose_name': 'صورة مراجعة',
                'verbose_name_plural': 'صور المراجعات',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='مفيد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review', verbose_name='المراجعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تصويت مفيد',
                'verbose_name_plural': 'تصويتات مفيدة',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
